### Dropwizard skeleton configuration file
##
## Do not commit changes that contain credentials or sensitive data!

server:
  rootPath: /api/v0/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2
  adminConnectors:
    - type: https
      port: 8081
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2

logging:
  loggers:
      org.hibernate.SQL: ALL
  appenders:
    - type: console
      threshold: ALL
      target: stdout
    - type: file
      currentLogFilename: logs/persons-api.log
      archivedLogFilenamePattern: logs/persons-api-%d.log.gz
      archivedFileCount: 5
      threshold: ALL
      timeZone: PST

authentication:
  - username: username
    password: password

api:
  endpointUri: https://api.oregonstate.edu/v1/

database:
  driverClass: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@//db-url
  user: dbuser
  password: dbpasswd
  properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
  validationQuery: "SELECT 1 FROM dual"
  initialSize: 2
  minSize: 1
  maxSize: 5

messageQueue:
  baseUrl: https://api.oregonstate.edu/v1/events
  apiKey: secretSauce
  newJobEventType: newJob

httpClientConfiguration:
  timeout: 150000ms
  connectionTimeout: 15000ms
  timeToLive: 1h
  cookiesEnabled: false
  maxConnections: 2
  maxConnectionsPerRoute: 2
  keepAlive: 0ms
  retries: 0
  userAgent: persons-api
