### Dropwizard skeleton configuration file
##
## Do not commit changes that contain credentials or sensitive data!

server:
  rootPath: /api/v0/*
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2
  adminConnectors:
    - type: https
      port: 8081
      keyStorePath: /path/to/development.keystore
      keyStorePassword: password
      certAlias: development
      trustStorePath: /path/to/development.truststore
      supportedProtocols:
        - TLSv1.1
        - TLSv1.2

logging:
  loggers:
      org.hibernate.SQL: ALL
  appenders:
    - type: console
      threshold: ALL
      target: stdout
    - type: file
      currentLogFilename: logs/persons-api.log
      archivedLogFilenamePattern: logs/persons-api-%d.log.gz
      archivedFileCount: 5
      threshold: ALL
      timeZone: PST

authentication:
  - username: username
    password: password

api:
  endpointUri: https://api.oregonstate.edu/v1/

readDatabase:
# Database configuration for database that is for reading (GET requests)
  driverClass: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@//db-url
  user: dbuser
  password: dbpasswd
  properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
  validationQuery: "SELECT 1 FROM dual"
  initialSize: 2
  minSize: 1
  maxSize: 5

writeDatabase:
# Database configuration for database that accepts write operations (POST, PUT, and DELETE requests)
  driverClass: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@//db-url
  user: dbuser
  password: dbpasswd
  properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
  validationQuery: "SELECT 1 FROM dual"
  initialSize: 2
  minSize: 1
  maxSize: 5