server:
  protocol: https
  hostname: ${API_HOSTNAME}
  port: ${PORT}
  adminPort: ${ADMIN_PORT}
  basePathPrefix: /api
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: ${USER}
  password: ${PASSWD}

dataSources:
  dataSources: ['oracledb']
  oracledb:
    poolMin: 4
    poolMax: 4
    poolIncrement: 0
    oracleSources: ['banner', 'ods']
    banner:
      connectString: ${BANNER_URL}
      user: ${BANNER_USER}
      password: ${BANNER_PASSWD}
    ods:
      connectString: ${ODS_URL}
      user: ${ODS_USER}
      password: ${ODS_PASSWD}
