server:
  protocol: https
  hostname: ${API_HOSTNAME}
  port: ${PORT}
  adminPort: ${ADMIN_PORT}
  basePathPrefix: /api
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: ${USER}
  password: ${PASSWD}

dataSources:
  dataSources: ['json', 'oracledb', 'awsS3']
  json:
    dbPath: 'db/mock-data.json'
  oracledb:
    connectString: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASSWD}
    poolMin: 4
    poolMax: 4
    poolIncrement: 0
  awsS3:
    bucket: bucketName
    apiVersion: '2006-03-01'
    accessKeyId: ${ACCESS_KEY_ID}
    secretAccessKey: ${SECRET_ACCESS_KEY}
    region: us-west-2
    # These values are for local or proxy S3 instances
    endpoint: null
    s3ForcePathStyle: false
