server:
  protocol: https
  hostname: ${API_HOSTNAME}
  port: ${PORT}
  adminPort: ${ADMIN_PORT}
  basePathPrefix: /api
  keyPath: /path/to/key.pem
  certPath: /path/to/server.crt
  secureProtocol: TLSv1_2_method

authentication:
  username: ${USER}
  password: ${PASSWD}

dataSources:
  dataSources: ['oracledb']
  oracledb:
    poolMin: 4
    poolMax: 4
    poolIncrement: 0
    oracleSources: ['bannerRead', 'odsRead']
    bannerRead:
      connectString: ${DB_URL}
      user: ${DB_USER}
      password: ${DB_PASSWD}
    odsRead:
      connectString: ${DB_URL}
      user: ${DB_USER}
      password: ${DB_PASSWD}
