const fakeOsuId = '999999999';
const fakeBaseUrl = '/v2';
const rawPerson = {
  displayFirstName: 'Lord',
  displayMiddleName: null,
  displayLastName: 'Voldemort',
  osuId: fakeOsuId,
  firstName: 'Tom',
  middleName: 'Marvolo',
  lastName: 'Riddle',
  birthDate: '1926-12-31',
  confidentialInd: 'N',
  citizenCode: 'C',
  citizenDescription: 'Citizen',
  sex: 'M',
  onid: 'riddlet',
  currentStudentInd: 'N',
  employeeStatusCode: 'A',
  ssnStatus: 'valid',
  lastPaidDate: '2020-05-31',
};

const fakeMealPlanId = '1';
const rawMealPlan = {
  mealPlanId: fakeMealPlanId,
  mealPlan: '!OrangeCash',
  balance: '9000.1',
  'lastUsed.dateTime': '2019-03-21T10:53:06Z',
  'lastUsed.location': 'North_Porch_Cafe',
};

const fakeJobId = 'C51495-00';
const rawJob = {
  positionNumber: 'C51495',
  suffix: '00',
  effectiveDate: '2019-04-15',
  beginDate: '2018-10-03',
  endDate: '2019-04-15',
  'contractType.code': 'P',
  accruesLeaveInd: 'Y',
  contractBeginDate: null,
  contractEndDate: null,
  'campus.code': '02A',
  'campus.description': 'Corvallis',
  'status.code': 'T',
  personnelChangeDate: '2019-04-15',
  changeReasonCode: 'GEXCD',
  jobDescription: 'Temp Analyst Programmer',
  fullTimeEquivalency: '1',
  appointmentPercent: '100',
  'salary.step': '0',
  'salary.group.code': '21819A',
  'salary.group.description': 'Fiscal Year 2018-2019',
  strsAppointmentBasis: '12',
  'supervisor.osuId': '931376331',
  'supervisor.firstName': 'John',
  'supervisor.lastName': 'Smith',
  'supervisor.email': 'nobody@nobody.nobody',
  'supervisor.positionNumber': 'C17791',
  'supervisor.suffix': 'S0',
  'timesheet.current.code': '139010',
  'timesheet.current.description': 'GRD - Graduate School Admin',
  'timesheet.predecessor.code': '130370',
  'timesheet.pred.description': 'GRD - Graduate School',
  'homeOrganization.current.code': '121221',
  'homeOrganization.current.desc': 'JIS - Enterprise Computing Services',
  'homeOrganization.pred.code': '120430',
  'homeOrganization.pred.desc': 'JIS - Information Services',
  hourlyRate: '30',
  hoursPerPay: '173.33',
  'salary.assignment': '5199.9',
  'salary.paysPerYear': '12',
  'employeeClassification.code': 'XS',
  'employeeClass.shortDesc': 'TEMP',
  'employeeClass.longDesc': 'Temporary Support Staff',
  'employerIdentification.code': 'ORST',
  'employerId.description': 'Oregon State University',
  'salary.annual': '62398.8',
  'earningCode.effectiveDate': null,
  'earningCode.code': null,
  'earningCode.hours': null,
  'earningCode.shift': null,
  'earningCode.shortDescription': null,
  'earningCode.longDescription': null,
  'i9Form.code': 'R',
  'i9Form.date': '2016-05-27',
  'i9Form.expirationDate': null,
  'retirement.code': '31',
  'retirement.description': 'ER Paid OPSRP',
  classifiedInd: 'N',
  lastPaidDate: '2019-04-30',
  laborDistribution: [
    {
      title: 'GRD - Graduate School',
      effectiveDate: '2018-10-03',
      accountIndex: 'GRD231',
      fund: '021120',
      organization: '144010',
      account: '10520',
      program: '12300',
      activity: null,
      location: null,
      distributionPercent: '100',
    },
  ],
};

export {
  fakeOsuId,
  fakeBaseUrl,
  rawPerson,
  fakeMealPlanId,
  rawMealPlan,
  fakeJobId,
  rawJob,
};
